version: 0.2

phases:
  install:
    runtime-version:
      nodejs: latest
    commands:
      - npm install -g serverless
      - npm install
      - rm -rf node_modules/sharp
      - SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=linux --libc=glibc sharp
  build:
    on-failure: ABORT
    commands:
      - >
        serverless deploy --stage ${STAGE}
          --param="bot-token=${BOT_TOKEN}"
          --param="open-ai-key=${OPEN_AI_KEY}"
          --param="log-level=${LOG_LEVEL}"
      - >
        serverless info --stage ${STAGE}
          --param="bot-token=${BOT_TOKEN}"
          --param="open-ai-key=${OPEN_AI_KEY}"
          --param="log-level=${LOG_LEVEL}"
        | grep "endpoint: POST"
        | awk '{print $4}'
        | xargs -I {} curl --request POST --url "https://api.telegram.org/bot${BOT_TOKEN}/setWebhook" --data "{\"url\": \"{}\"}"
      - echo "WebHook linked successfully to the telegram bot"

cache:
  paths:
    - node_modules