version: 0.2

phases:
  install:
    runtime-version:
      nodejs: latest
    commands:
      - npm install -g serverless
      - npm install
  build:
    commands:
      - serverless deploy --stage ${STAGE}
        --param="bot-token=${BOT_TOKEN}"
        --param="open-ai-key=${OPEN_AI_KEY}"
        --param="log-level=${LOG_LEVEL}"

cache:
  paths:
    - node_modules