service: ai-conversation-bot

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  stage: ${self:custom.stage}
  deploymentBucket:
    name: sls-deploy-${opt:account, 'serverless'}-${self:provider.region}
    serverSideEncryption: AES256
  environment:
    BOT_TOKEN: ${param:bot-token}
    OPEN_AI_KEY: ${param:open-ai-key}
    LOG_LEVEL: ${param:log-level}
    AI_TEXT_MODEL: ${file(config/${self:custom.stage}.json):openai.textModel}
    AI_TEMPERATURE: ${file(config/${self:custom.stage}.json):openai.temperature}
    AI_MAX_TOKENS: ${file(config/${self:custom.stage}.json):openai.maxTokens}
    AI_FREQUENCY_PENALTY: ${file(config/${self:custom.stage}.json):openai.penalty.frequency}
    AI_PRESENCE_PENALTY: ${file(config/${self:custom.stage}.json):openai.penalty.presence}
    BUCKET_NAME: ${self:custom.names.user-context-bucket}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - arn:aws:s3:::${self:custom.names.user-context-bucket}*
        - arn:aws:s3:::${self:custom.names.user-context-bucket}/*

custom:
  stage: ${opt:stage, 'dev'}
  names:
    user-context-bucket: user-context-${self:custom.stage}

functions:
  botWebhook:
    handler: src/handler.botWebhook
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: conversation-webhook${self:provider.environment.BOT_TOKEN}
          method: post

resources:
  - ${file(template.yml)}

plugins:
  - serverless-plugin-typescript
  - serverless-deployment-bucket
  - serverless-plugin-include-dependencies
