Resources:
  UserContextBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.names.user-context-bucket}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  MessageTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ${self:custom.names.topic}
      DisplayName: ${self:custom.names.topic}